---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-folder
  namespace: default
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: loumaris/backup:psql-10
            args:
            - backup
            - perform
            - --trigger
            - folder
            env:
            - name: FTP_USERNAME
              value: user
            - name: FTP_PASSWORD
              value: password
            - name: FTP_SERVER
              value: server
            - name: FTP_PORT
              value: "21"
            - name: FTP_PATH
              value: /
            - name: BACKUP_FOLDER
              value: /mnt/
            - name: SLACK_URL
              value: https://slack.com/foo/bar
            volumeMounts:
            - mountPath: /mnt/
              name: storage
          volumes:
          - hostPath:
              path: /srv/path/for/backup
              type: ""
            name: storage
          restartPolicy: OnFailure


